### ISSUE TITLE
AWS SSO Sync/Login receiving 429 - TooManyRequestsException

### ISSUE THREAD

**Issue by peteawood** [Noovolari/leapp#281]
**Describe the bug**
After a successful login to my AWS SSO Integration, an HTTP 429 Unknown Code is displayed and nothing displays in the Session list. Initiating a Sync operation also exhibits the same behaviour. This is new behaviour without me upgrading my version of Leapp nor changing my local configuration. Prior to the 24th May Leapp worked as expected.

**Leapp Version**
0.12.1

**To Reproduce**
1. Correctly configure an AWS Single Sign On Integration
2. Login to the Integration and authenticate/allow Leapp.
3. The error will display
4. Try using the Sync menu option
5. The error will display again

**Expected behavior**
After a sync or login I expect the relevant roles and accounts I have access to to appear in the session window.

**Screenshots**
![image](https://user-images.githubusercontent.com/15778881/170303170-4450f43d-f437-4f41-9e19-e2cf73bd4bdc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 21H2 (19044.1706)
 - Leapp Version 0.12.1

**Additional context**
My first thought was that this is due to an increase in the accounts I have access to and Leapp is not throttling the amount of ListAccountRoles API calls being made. Judging by CloudTrail entries:

### Problem occurring (post 24th May)
~227 ListAccountRoles calls made in 3 seconds
~59 429 errors logged (majority in the final second)

### Problem not occurring (prior 24th May)
~177 ListAccountRoles calls made in 2 seconds
0 429 errors logged

The amount of roles/accounts I have access to has not increased by 50 (maybe increased 2-5). Looking into a few of the CloudTrail entries I can see that ListAccountRoles is being called more than once for at least 1 account where I only have 1 role.

I was struggling to class this as a bug or a feature request as it's not clear where the fault is but at the moment the SSO Integration (and therefore Leapp) is unusable for me so settled on bug. Relevant log entry attached.

[LeappLogExcerpt.txt](https://github.com/Noovolari/leapp/files/8772720/LeappLogExcerpt.txt)

**Comment by andreacavagna01** [comment]
Interesting Bug! thanks for the clarification. It's a limitation added by AWS Single Sign-On in the last week.
We will look at it and I think is something that can be solved by slowing down the request number of API calls to AWS SSO sdk. 

Thanks for reporting it

**Comment by peteawood** [comment]
Thanks @andreacavagna01! I did an extremely basic fix (pausing for 5 seconds every 25 calls) which seemed to resolve it so would agree with the approach 👍 Although maybe something with more sensible figures and that potentially remains responsive rather than my "let it hang until completed" approach! 😄

**Comment by peteawood** [comment]
Yes but not to the same degree. I still see Throttling Errors in CloudTrail but they are fewer and the SSO Login eventually succeeds (although it does take a while with no feedback).

Since Leapp is usable again I'm happy if you would prefer to close this bug report and I can open a feature request for some sort of progress bar during SSO Integration logins which should also aim to address the throttling problem?

**Comment by jessepiccolo** [comment]
This is a issue for me as well.  I have 180+ AWS accounts for SSO and only growing.

**Comment by jessepiccolo** [comment]
@peteawood could you please show how you added the pause?  This bug killed the app for me...  Just doesn't work with a lot of accounts.

**Comment by andreacavagna01** [comment]
I'll open a Branch linked to this issue in which we can discuss about the best solution

**Comment by andreacavagna01** [comment]
fixed in the PR and will be released soon

**Comment by egauk** [comment]
This is an issue for me running 0.13.1, 200+ AWS accounts

**Comment by tscully49** [comment]
Same here, still problem with 0.13.1 and we are only loading ~75 accounts. It unfortunately is making the app unusable for new users in the company.

**Comment by pethron** [comment]
Sorry to hear that, we'll check again

**Comment by ericvilla** [comment]
Hi everyone! We've just released 0.13.2 version of the Desktop App. It solves the issue reported in the current issue and in the #308 one. @egauk, @tscully49, @jessepiccolo, @peteawood I invite you to test it with your AWS SSO (ops... Identity Center) organization. Let me know if it works now. I'll re-open the issue if you still encounter problems. Thank you!

**Comment by Kimnor** [comment]
So I understand this is closed however I am getting this error on my mac and I am on version 18.3.  I cant give an exact date when this started because I have ignored it for so long.  Just thought I would report that I still see this error.
![image](https://github.com/Noovolari/leapp/assets/43546434/f6f6310e-af73-45aa-ad20-1fee0c32786b)

**Comment by andreacavagna01** [comment]
Thanks for reporting it! We have already fixed this problem in version 0.18.5. Download it and let me know if this is fixed
