### ISSUE TITLE
Update notification steals focus

### ISSUE THREAD

**Issue by itsthejoker** [Noovolari/leapp#373]
**Describe the bug**

When the update notification fires, it brings the application to the foreground and steals focus from the current application in use.

**Leapp Version**
0.15.0

**To Reproduce**
1. Have Leapp open in the background
2. Wait until new version becomes available
3. Wait for Leapp to check for updates
4. Observe focus being stolen

**Expected behavior**

The notification should be there, but should appear under the current focus and become apparent when I next go back to Leapp.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Monterey
 - OS Version [e.g. 22] 12.6
 - Leapp Version [e.g. 0.2.5] 0.15.0

**Comment by urz9999** [comment]
Hi @itsthejoker, sorry for the late response we where away for Christmas stop, we'll check and add it to our tech debt list.  I think it could resolved in the next release

**Comment by pethron** [comment]
Changed label as an enhancement. We see this behavior in other desktop applications, so we'll consider the suggestion for future releases. Thank you.

**Comment by itsthejoker** [comment]
A bad UX decision is a bad UX decision, regardless if other applications make do it. At least it's in the list. Thanks.

**Comment by itsthejoker** [comment]
@pethron @urz9999 I'd like to revisit this issue -- today it fired roughly 10 minutes after I opened the app and ripped focus away from my editor that I was using in its own MacOS space; my entire desktop switched back to Leapp so that it could tell me that there was a new update. This is _very_ frustrating.

I don't have anything against notifications about new updates -- those are important -- but can we split the difference and maybe switch to a system toast notif that doesn't steal focus?

**Comment by itsthejoker** [comment]
This is still an issue; are there any plans on the roadmap to resolve it?
